name: Ragsync Verification

on:
  workflow_dispatch:  # Allow manual workflow trigger
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight every Sunday

jobs:
  check-ragsync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download Ragsync binary
        run: |
          wget https://oss-qn.yaklang.com/ragsync/v1.0.3/ragsync_linux_amd64 -O ragsync
          chmod +x ragsync
      
      - name: Verify Ragsync command
        run: |
          ./ragsync sync -h
      
      - name: Load Ragsync Config
        run: |
          mkdir -p ~/.ragsync
          echo "${{ secrets.RAGSYNC_CONFIG }}" | base64 -d > ~/.ragsync/ragsync.yaml
          echo "Config loaded to ~/.ragsync/ragsync.yaml"
      
      - name: Validate Ragsync Config
        run: |
          ./ragsync validate
          if [ $? -ne 0 ]; then
            echo "Ragsync config validation failed"
            exit 1
          fi
          echo "Ragsync config validation passed"
      
      - name: Run Ragsync Sync
        run: |
          ./ragsync sync --dir ./library-usage
      
      - name: Run Ragsync Sync
        run: |
          ./ragsync sync --dir ./practice
      
      - name: Run Ragsync yaklang-website
        run: |
          ./ragsync sync --dir ./yaklang-website
      
      - name: Run Ragsync yaklang-website
        run: |
          ./ragsync sync --dir ./articles